### ISSUE TITLE
Fix Buttons

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [ThePixelMoon/OpenMod#2]
when I press 1 button and I cant click the rest

**Comment by ThePixelMoon** [comment]
Exactly

**Comment by ThePixelMoon** [comment]
I'll try to fix it tomorrow, thanks for the issue.

**Comment by GuestSneezeOSDev** [comment]
Could you create a loading.html for the loading screens as well?

**Comment by ThePixelMoon** [comment]
Fixed in https://github.com/ThePixelMoon/OpenMod/commit/c347b4758ca20028ed6f33f352322c456f5e96d0.
